### ISSUE TITLE
pixi build fails in the provider docker image - "could not initialize the build-backend"

### ISSUE THREAD

**Issue by abiesylvera** [prefix-dev/pixi#4683]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Following the example [here](https://pixi.sh/dev/build/python/#adding-a-pixitoml) on building a python package fails when `pixi build` is run in the laste provided docker image. 

### Issue description

Following the example 

```shell
root@58adabd079db:~# cd python_rich/
root@58adabd079db:~/python_rich# pixi build 
Error:   x could not initialize the build-backend
  |->   x failed to communicate with the build backend (pixi-build-python)
  |     help: Ensure that the build backend implements the JSON-RPC protocol correctly.
  |   
  `-> The background task closed EOF; restart required
```

### Expected behavior

The package builds.

**Comment by abiesylvera** [comment]
Seems to be an issue with with 0.55.0 as dropping my docker image down to `ghcr.io/prefix-dev/pixi:0.54.2-bookworm` makes the build work again.

**Comment by yjeand** [comment]
Hello, I have the same error on a custom docker image based on `ubuntu:focal`. I have tried several versions of pixi, including the 0.54.2, but I still get the error each time.

Is there something specific to do to get `pixi build` to work inside a docker container?

**Comment by ruben-arts** [comment]
It might be related with the version of Pixi vs the version of the build backend. 
We've released `0.56.0` and rebuild all backends. You should be able to fetch the correct one now.

**Comment by yjeand** [comment]
Thank you @ruben-arts 

We've tried again with pixi 0.56.0, it downloads pixi-build-python@0.4.0, but still no luck.

**Comment by ruben-arts** [comment]
Do you still get the exact same error?<br><br>If so could you share the `pixi info` output of the machine?

**Comment by connor-stewarty** [comment]
Hello @ruben-arts, I am receiving the same error using the [Building a Python Package
 Tutorial](https://pixi.sh/dev/build/python/). I am using a RHEL 8.10 system, but I experience the same thing on a RHEL8 container image. The error does not seem to occur on RHEL 9.
```
Error:  × could not initialize the build-backend
  │   
  ├─▶   × failed to communicate with the build backend (pixi-build-python)
  │     help: Ensure that the build backend implements the JSON-RPC protocol correctly.
  │   
  ╰─▶ The background task closed EOF; restart required
```

Here is my pixi info:
```
System
------------
       Pixi version: 0.56.0
           Platform: linux-64
   Virtual packages: __unix=0=0
                   : __linux=4.18.0=0
                   : __glibc=2.28=0
                   : __archspec=1=cascadelake
          Cache dir: /home/user/.cache/rattler/cache
       Auth storage: /home/user/.rattler/credentials.json
   Config locations: No config files found

Global
------------
            Bin dir: /home/user/.pixi/bin
    Environment dir: /home/user/.pixi/envs
       Manifest dir: /home/user/.pixi/manifests/pixi-global.toml

Workspace
------------
               Name: python_rich
      Manifest file: /home/user/git/dependencies/python_rich/pixi.toml

Environments
------------
        Environment: default
           Features: default
           Channels: https://prefix.dev/conda-forge
   Dependency count: 1
       Dependencies: python_rich
   Target platforms: osx-arm64, osx-64, win-64, linux-64
    Prefix location: /home/user/git/dependencies/python_rich/.pixi/envs/default
              Tasks: start
```

Is there something I need to do to allow `pixi build` to work in this environment?

**Comment by yjeand** [comment]
Hello @ruben-arts, thank you for your support. Here is the information you requested.

We still get the exact same error when we try to use the “pixi build” inside a docker container when it downloads `pixi-build-python@0.4.0` as shown here:

<img width="1495" height="202" alt="Image" src="https://github.com/user-attachments/assets/91a78727-4451-40c1-9353-90296afdbf33" />

And here is the pixi info output of the machine:

<img width="1485" height="591" alt="Image" src="https://github.com/user-attachments/assets/30d96733-b765-4460-ad11-27952f13b84a" />

As you can see, we are using our company's internal Artifactory mirror for both the `conda-forge` and `pixi-build-backend` channels, maybe it is related to the problem?

**Comment by ruben-arts** [comment]
@baszalmstra could you take a look at this?

**Comment by yjeand** [comment]
Update: `pixi build` works fine for us now in a docker container, using pixi v0.59.0 and pixi-build-python 0.4.1.

I don't know what you did, but obviously it worked. Thank you very much!

**Comment by baszalmstra** [comment]
Ah I forgot to update this issue. The reason it works now is because the backends now link against a much older version of glibc.
